options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 1

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 1
  single-line-per-selector: 1

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 1
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 1
  no-debug: 1
  no-disallowed-properties: 0
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements: 1
  no-trailing-whitespace: 1
  no-trailing-zero: 1
  no-transition-all: 1
  no-universal-selectors: 0
  no-url-domains: 1
  no-url-protocols: 1
  no-vendor-prefixes: 1
  no-warn: 1
  property-units: 0

  # Nesting
  declarations-before-nesting: 1
  force-attribute-nesting: 1
  force-element-nesting: 1
  force-pseudo-nesting: 1

  # Name Formats
  class-name-format: 1
  function-name-format: 1
  id-name-format: 0
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format: 0

  # Style Guide
  attribute-quotes: 1
  bem-depth: 0
  border-zero: 1
  brace-style: 1
  clean-import-paths: 1
  empty-args: 1
  hex-length: 1
  hex-notation: 1
  indentation: 1
  leading-zero: 1
  max-line-length: 0
  max-file-line-count: 0
  nesting-depth: 1
  property-sort-order:
    - 1
    -
      order:
        - 'content'
        - 'position'
        - 'top'
        - 'right'
        - 'bottom'
        - 'left'
        - 'z-index'
        - 'overflow'
        - 'overflow-x'
        - 'overflow-y'
        - 'display'
        - 'flex-direction'
        - 'justify-content'
        - 'align-items'
        - 'flex-wrap'
        - 'float'
        - 'width'
        - 'height'
        - 'max-width'
        - 'max-height'
        - 'min-width'
        - 'min-height'
        - 'padding'
        - 'padding-top'
        - 'padding-right'
        - 'padding-bottom'
        - 'padding-left'
        - 'margin'
        - 'margin-top'
        - 'margin-right'
        - 'margin-bottom'
        - 'margin-left'
        - 'margin-collapse'
        - 'margin-top-collapse'
        - 'margin-right-collapse'
        - 'margin-bottom-collapse'
        - 'margin-left-collapse'
        - 'border'
        - 'border-collapse'
        - 'border-top'
        - 'border-right'
        - 'border-bottom'
        - 'border-left'
        - 'border-color'
        - 'border-image'
        - 'border-top-color'
        - 'border-right-color'
        - 'border-bottom-color'
        - 'border-left-color'
        - 'border-spacing'
        - 'border-style'
        - 'border-top-style'
        - 'border-right-style'
        - 'border-bottom-style'
        - 'border-left-style'
        - 'border-width'
        - 'border-top-width'
        - 'border-right-width'
        - 'border-bottom-width'
        - 'border-left-width'
        - 'border-radius'
        - 'border-top-right-radius'
        - 'border-bottom-right-radius'
        - 'border-bottom-left-radius'
        - 'border-top-left-radius'
        - 'border-radius-topright'
        - 'border-radius-bottomright'
        - 'border-radius-bottomleft'
        - 'border-radius-topleft'
        - 'background'
        - 'background-attachment'
        - 'background-color'
        - 'background-image'
        - 'background-position'
        - 'background-repeat'
        - 'background-size'
        - 'clip'
        - 'clear'
        - 'color'
        - 'font'
        - 'font-family'
        - 'src'
        - 'font-size'
        - 'font-smoothing'
        - 'osx-font-smoothing'
        - 'font-weight'
        - 'font-style'
        - 'hyphens'
        - 'line-height'
        - 'letter-spacing'
        - 'word-spacing'
        - 'text-align'
        - 'text-decoration'
        - 'text-indent'
        - 'text-overflow'
        - 'text-rendering'
        - 'text-size-adjust'
        - 'text-shadow'
        - 'text-transform'
        - 'word-break'
        - 'word-wrap'
        - 'white-space'
        - 'vertical-align'
        - 'list-style'
        - 'list-style-type'
        - 'list-style-position'
        - 'list-style-image'
        - 'pointer-events'
        - 'cursor'
        - 'quotes'
        - 'outline'
        - 'outline-offset'
        - 'opacity'
        - 'visibility'
        - 'size'
        - 'zoom'
        - 'transform'
        - 'box-align'
        - 'box-flex'
        - 'box-orient'
        - 'box-pack'
        - 'box-shadow'
        - 'box-sizing'
        - 'table-layout'
        - 'filter'
        - 'animation'
        - 'animation-delay'
        - 'animation-duration'
        - 'animation-iteration-count'
        - 'animation-name'
        - 'animation-play-state'
        - 'animation-timing-function'
        - 'animation-fill-mode'
        - 'transition'
        - 'transition-delay'
        - 'transition-duration'
        - 'transition-property'
        - 'transition-timing-function'
        - 'background-clip'
        - 'backface-visibility'
        - 'resize'
        - 'appearance'
        - 'user-select'
        - 'interpolation-mode'
        - 'direction'
        - 'marks'
        - 'page'
        - 'set-link-source'
        - 'unicode-bidi'
        - 'speak'
  pseudo-element: 1
  quotes: 1
  shorthand-values: 0
  url-quotes: 1
  variable-for-property: 1
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1
  space-around-operator: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
